@todo_app.Server_HostAddress = http://localhost:5210

GET {{todo_app.Server_HostAddress}}/task/getTaskList
Accept: application/json

###

POST {{todo_app.Server_HostAddress}}/task/
Content-Type: application/json

{
    "Id": 3,
    "Name": "Taaaask",
    "Priority": 1,
    "Status": 0
}

###

PUT {{todo_app.Server_HostAddress}}/task/3/edit
Content-Type: application/json

{
    "Id": 3,
    "Name": "Taaaaask",
    "Priority": 1,
    "Status": 2
}

###

DELETE {{todo_app.Server_HostAddress}}/task/3/delete
Content-Type: application/json

###